# rubocop todo:
#
Lint/AmbiguousRegexpLiteral:
  Exclude:
    - 'test/integration/dynamodb_table_create/rspec/dynamodb_table_create_spec.rb'
    - 'test/integration/dynamodb_table_update/rspec/dynamodb_table_update_spec.rb'
    - 'test/integration/s3_file/default_spec.rb'

Lint/Loop:
  Exclude:
    - 'providers/ebs_raid.rb'

Lint/ParenthesesAsGroupedExpression:
  Exclude:
    - 'test/fixtures/cookbooks/aws_test/recipes/dynamodb_table_create.rb'
    - 'test/fixtures/cookbooks/aws_test/recipes/dynamodb_table_update.rb'

Lint/UselessAssignment:
  Exclude:
    - 'libraries/ec2.rb'

# Configuration parameters: CountKeywordArgs.
Metrics/ParameterLists:
  Max: 15
